from BinarySearchTree import BinarySearchTree


bst = BinarySearchTree()

bst.insert(12)
bst.insert(18)
bst.insert(22)
bst.insert(30)
bst.insert(39)
bst.insert(42)
bst.insert(50)
bst.insert(60)
bst.insert(76)
bst.insert(81)
bst.insert(82)
bst.insert(88)
bst.insert(90)
bst.insert(99)

print('POST-ORDER:')
bst.print_post_order()
print('PRE-ORDER:')
bst.print_pre_order()
print('IN-ORDER:')
bst.print_in_order()

bst.balance_tree()
print('\nTREE HAS BEEN BALANCED!\n')

print('POST-ORDER:')
bst.print_post_order()
print('PRE-ORDER:')
bst.print_pre_order()
print('IN-ORDER:')
bst.print_in_order()

bst.remove(12)
bst.remove(76)
bst.remove(88)
bst.remove(90)

print('\nREMOVED 12, 76, 88 AND 90\n')
print('POST-ORDER:')
bst.print_post_order()
print('PRE-ORDER:')
bst.print_pre_order()
print('IN-ORDER:')
bst.print_in_order()

bst.remove(50)
print('\nREMOVED TREE ROOT\n')
print('POST-ORDER:')
bst.print_post_order()
print('PRE-ORDER:')
bst.print_pre_order()
print('IN-ORDER:')
bst.print_in_order()
