from DoubleLinkedList import DoubleLinkedList

linked_list = DoubleLinkedList(7)
linked_list.insert_at_start(10)
linked_list.insert_at_start(5)
linked_list.insert_at_end(15)
# print(linked_list.contains(5))
# linked_list.insert_before_current(4.9)
# print(linked_list.contains(10))
# linked_list.insert_before_current(9.9)
linked_list.print_list()
linked_list.insert(2, 7.5)
linked_list.insert(4, 12.5)
linked_list.insert(6, 17.5)
linked_list.insert(1, 2.5)
linked_list.print_list()
# linked_list.print_list()
# linked_list.insert_at_end('error')
